# Setting coverage targets per flag
coverage:
    status:
      project:
        default: 
          target: 70% #overall project/ repo coverage
        front:
          target: 70%
          flags:
            - frontend
        back-end:
          target: 70%
          flags:
            - backend
  
# adding Flags to your `layout` configuration to show up in the PR comment
comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  
    require_base: yes
    require_head: yes       
    branches: null
  
# New root YAML section = `flags:`
# This is where you would define every flag from your
# uploader, and update when new Flags added
flags:
    frontend:
      paths: #note, accepts globs, not regexes
        - front/*
      carryforward: true
    backend:
      paths: #note, accepts globs, not regexes
        - back/*
      carryforward: true
      
  