
name: Back Build & Test

on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    back-build-test:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: write
          checks: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Back Install Dependencies
              run: mvn clean install
              working-directory: back

            - name: Back Build
              run: mvn clean package
              working-directory: back

            - name: Back Test
              run: mvn clean test
              working-directory: back

            - name: Upload Back coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: backend
                working-directory: back

            - name: JUnit Test Report
              uses: phoenix-actions/test-reporting@v8
              id: junit-test-report
              if: success() || failure()
              with:
                name: JUNIT Tests
                path: 'target/site/jacoco/*.*'
                reporter: jest-junit
                working-directory: back

            - name: Read output variables
              run: |
                echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"

            
            