
name: Build & Test
run-name: Build & Test

on: 
  push:
      branches:
          - main
  pull_request:
      branches:
          - main

jobs:
    back-build-test:
        runs-on: ubuntu-latest
        defaults:
          run:
              working-directory: back

        permissions:
          id-token: write
          contents: write
          checks: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                java-version: 11
                distribution: 'zulu'
                cache: maven

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-m2

            - name: Back Install Dependencies
              run: mvn -B clean install

            - name: Back Build
              run: mvn -B clean package --file pom.xml

            - name: Back Test
              id: back-test
              run: mvn -B clean test

            - name: 'back report: commit and push'
              run: |
                  git config user.name "${{ secrets.GIT_USER_NAME }}"
                  git config user.email "${{ secrets.GIT_USER_EMAIL }}"
                  git pull
                  if test -d ${{ github.workspace }}/back/target_site; then rm -rf target_site; fi
                  mv target/site target_site
                  git add .
                  git commit -m "add jacoco report"
                  git push origin main            

            - name: Read output variables
              run: |
                echo "Total coverage ${{ steps.back-test.outputs.coverage-overall }}"
                echo "Changed Files coverage ${{ steps.back-test.outputs.coverage-changed-files }}"

    front-build-test:
      needs: back-build-test

      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: front

      permissions:
        id-token: write
        contents: write
        checks: write

      steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '14.x'
              cache: 'npm'
              cache-dependency-path: '**/package-lock.json'

          - name: Cache Node modules
            uses: actions/cache@v4
            with:
              path: front/node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-node-

          - name: Front Install Dependencies
            run: npm install

          - name: Front Build
            run: npm run build

          - name: Front Test
            run: npm run test -- --code-coverage=true --watch=false --browsers=ChromeHeadless

          - name: 'front report: commit and push'
            run: |
              git config user.name "${{ secrets.GIT_USER_NAME }}"
              git config user.email "${{ secrets.GIT_USER_EMAIL }}"
              git pull
              if test -d ${{ github.workspace }}/front/coverage_; then rm -rf coverage_; fi
              mv coverage coverage_
              git add .
              git commit -m "add karma report"
              git push origin main

          
