
name: Build and Test

on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: write
          checks: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Back Install Dependencies
              run: mvn clean install
              working-directory: back

            - name: Back Build
              run: mvn clean package
              working-directory: back

            - name: Back Test
              run: mvn clean test -DEBUG=mocha*
              working-directory: back

            - name: JUnit Test Report
              uses: phoenix-actions/test-reporting@v8
              id: junit-test-report
              if: success() || failure()
              with:
                name: JUNIT Tests
                path: '**/target/site/jacoco/index.html'
                reporter: jest-junit
                working-directory: back

            - name: Read output variables
              run: |
                echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"

            - name: Front Install Dependencies
              run: npm install
              working-directory: front

            - name: Front Build
              run: npm run build
              working-directory: front

            - name: Front Test
              run: npm run test -- --code-coverage=true --watch=false --browsers=ChromeHeadless
              working-directory: front

            # - name: Jest Test Report
            #   uses: phoenix-actions/test-reporting@v8
            #   id: jest-test-report
            #   if: success() || failure()
            #   with:
            #     name: JEST Tests
            #     path: '**/coverage/bobapp/index.html'
            #     reporter: jest-junit 
            #     working-directory: front

            # - name: Read output variables
            #   run: |
            #     echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"

