
name: Build & Test

on: 
  push:
      branches:
          - main
  pull_request:

jobs:
    back-build-test:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: write
          checks: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                java-version: 11
                distribution: 'zulu'

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-m2

            - name: Back Install Dependencies
              run: mvn clean install
              working-directory: back

            - name: Back Build
              run: mvn clean package --file pom.xml
              working-directory: back

            - name: Back Test
              run: mvn clean test
              working-directory: back

            - name: Upload Back coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: backend
                working-directory: back

            - name: List front files 
              run: |
                ls ${{ github.workspace }}/back/target/site/jacoco/*

            # - name: JUnit Test Report
            #   uses: phoenix-actions/test-reporting@v8
            #   id: junit-test-report
            #   if: success() || failure()
            #   with:
            #     name: JUNIT Tests
            #     path: 'target/site/jacoco/*.*'
            #     reporter: jest-junit
            #     working-directory: back

            # - name: Read output variables
            #   run: |
            #     echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"

    front-build-test:
      runs-on: ubuntu-latest

      permissions:
        id-token: write
        contents: write
        checks: write

      steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Front Install Dependencies
            run: |
              npm install
              npm i karma-coverage-istanbul-reporter --save-dev
            working-directory: front

          - name: Front Build
            run: npm run build
            working-directory: front

          - name: Front Test
            run: npm run test -- --code-coverage=true --watch=false --browsers=ChromeHeadless
            working-directory: front

          - name: List front files 
            run: |
              ls ${{ github.workspace }}/front/coverage/bobapp

          - name: Upload Front coverage to Codecov
            uses: codecov/codecov-action@v4
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
              flags: frontend
              working-directory: front

          # - name: Jest Test Report
          #   uses: phoenix-actions/test-reporting@v8
          #   id: jest-test-report
          #   if: success() || failure()
          #   with:
          #     name: JEST Tests
          #     path: 'coverage/bobapp/*.*' 
          #     # path: 'coverage/bobapp/*.*,coverage/bobapp/app/*.*,coverage/bobapp/app/**/*.*' 
          #     reporter: jest-junit 
          #     working-directory: front

          # - name: Read output variables
          #   run: |
          #     echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"


            
            