
name: Build and Test

on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Back Install Dependencies
              run: mvn clean install
              working-directory: back

            - name: Back Build
              run: mvn clean package
              working-directory: back

            - name: Back Test
              run: mvn clean test
              working-directory: back

            - name: Front Install Dependencies
              run: npm install
              working-directory: front

            - name: Front Build
              run: npm run build
              working-directory: front

            - name: Front Test
              run: npm run test -- --watch=false --browsers=ChromeHeadless
              working-directory: front

            - name: Test Report
              uses: phoenix-actions/test-reporting@v8
              id: test-report
              if: success() || failure()
              with:
                name: JEST Tests
                path: reports/jest-*.xml
                reporter: jest-junit 

            - name: Read output variables
              run: |
                echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"

