
name: Docker Deployment
run-name: Docker Deployment

on:
  workflow_run:
    workflows: ["Sonar Cloud"]
    types:
      - completed

jobs:
  back-docker-deployment:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: back
  
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN_BACK }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ${{ github.workspace }}/back/
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest
  
  
  front-docker-deployment:
      needs: back-docker-deployment
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: front
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN_FRONT }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ${{ github.workspace }}/front/
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
  
    




