
name: Front Build & Test

on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    front-build-test:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: write
          checks: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Front Install Dependencies
              run: npm install
              working-directory: front

            - name: Front Build
              run: npm run build
              working-directory: front

            - name: Front Test
              run: npm run test -- --code-coverage=true --watch=false --browsers=ChromeHeadless
              working-directory: front

            - name: List front files 
              run: |
                ls ${{ github.workspace }}/front/dist/bobapp/*

            - name: Upload Front coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: frontend
                working-directory: front

            # - name: Jest Test Report
            #   uses: phoenix-actions/test-reporting@v8
            #   id: jest-test-report
            #   if: success() || failure()
            #   with:
            #     name: JEST Tests
            #     path: '**/coverage/bobapp/index.html'
            #     reporter: jest-junit 
            #     working-directory: front

            # - name: Read output variables
            #   run: |
            #     echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"

            # Run ls /home/runner/work/bob-app/bob-app/front/dist/*
            #   ls /home/runner/work/bob-app/bob-app/front/dist/*
            #   shell: /usr/bin/bash -e {0}
            # 3rdpartylicenses.txt
            # favicon.ico
            # index.html
            # main.74c3c92c4e401b76.js
            # polyfills.595773b29d44bac7.js
            # runtime.9c033397618380e0.js
            # styles.5f698423e5103cba.css

