
name: Front Build & Test

on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    front-build-test:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [16.x]

        permissions:
          id-token: write
          contents: write
          checks: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 2
        
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: Front Install Dependencies
              run: npm install
              working-directory: front

            - name: Front Build
              run: npm run build
              working-directory: front

            - name: Front Test
              run: npm run test -- --code-coverage=true --watch=false --browsers=ChromeHeadless
              working-directory: front

            - name: Upload Front coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: frontend
                working-directory: front

            # - name: Jest Test Report
            #   uses: phoenix-actions/test-reporting@v8
            #   id: jest-test-report
            #   if: success() || failure()
            #   with:
            #     name: JEST Tests
            #     path: '**/coverage/bobapp/index.html'
            #     reporter: jest-junit 
            #     working-directory: front

            # - name: Read output variables
            #   run: |
            #     echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"

